# Generated by Django 4.0.3 on 2022-05-21 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, default='', verbose_name='bio'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.FilePathField(blank=True, null=True, verbose_name='profile_image'),
        ),
    ]
